-- =========================================================================
-- (Sanitized 2026-09-29) One-off credit-card rollover data correction.
--
-- This migration fixed a single user's card (wrong rollover charge, due_date
-- left at the deduction day instead of the deadline) and their ledger_states
-- mirror. It was applied to the production database on 2026-09-11 and is a
-- NO-OP on any fresh replay: a new database has none of the affected rows.
--
-- The original body embedded personal financial data (real balances and
-- record ids) and was therefore removed from the working tree. The fix logic,
-- for reference, was:
--   1) delete the stray credit_card_charge transaction written by the old
--      due-date-anchored rollover logic (exact row by id + reference_id);
--   2) set the card's post-payment balance, 7th-anchored due_date and 5%
--      min_payment;
--   3) mirror the same values into ledger_states.state (transactions filter +
--      cards array update), guarded and idempotent.
--
-- The rollover logic itself was fixed in src/lib/creditCards.ts (DEDUCTION_DAY
-- / paymentsInCycle), which is the durable change here.

SELECT 1;
